#!/usr/bin/expect -f
# runs the load and unload scripts, ensuring that turbo boost is disabled
# (must be unload before load because sometimes it will stop working, even
# while technically loaded)
set timeout -15
set password [lindex $argv 0]
set scriptdir [lindex $argv 1]

spawn sudo "$scriptdir/unload.sh"
sleep 3
expect "Password:"
send "$password\r"
interact

spawn sudo "$scriptdir/load.sh"
sleep 3
expect "Password:"
send "$password\r"
interact
